seed = 7

[data]
path = "data/house"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.09862224026902408
depth = 6
l2_leaf_reg = 6.088685399811386
leaf_estimation_iterations = 6
learning_rate = 0.044212191600031224

[catboost_fit]
logging_level = "Verbose"
