seed = 11

[data]
path = "data/microsoft"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.5129608983696669
gamma = 0
lambda = 2.0199389994187804
learning_rate = 0.014018047468256538
max_depth = 10
min_child_weight = 4.953715793750007
subsample = 0.8866969946884005

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
