seed = 7

[data]
path = "data/covtype"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.30940101064924114
depth = 10
l2_leaf_reg = 5.60504544483669
leaf_estimation_iterations = 7
learning_rate = 0.19694454211281873

[catboost_fit]
logging_level = "Verbose"
