seed = 9

[data]
path = "data/weather-small"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 32
bagging_temperature = 0.21682442007523126
depth = 10
l2_leaf_reg = 3.542400827684336
leaf_estimation_iterations = 2
learning_rate = 0.11315092947098153
random_seed = 0

[catboost_fit]
logging_level = "Verbose"
