seed = 8

[data]
path = "data/covtype"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.8741049013874842
gamma = 0
lambda = 0.2535418039302976
learning_rate = 0.08488698487297466
max_depth = 10
min_child_weight = 0.004870699190932097
subsample = 0.8456635178673468

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
