seed = 0
program = "bin/mask.py"
n_trials = 100

[base_config]
seed = 0

[base_config.data]
T_cache = true
path = "data/house"

[base_config.data.T]
normalization = "quantile"

[base_config.training]
batch_size = 128

[base_config.model]
kind = "resnet"

[base_config.model.config]
d_main = 512

[base_config.pretrain]
corrupt_strategy = "resample"
patience = 2
d_hidden_head = 512

[space.model.config]
n_blocks = [
    "int",
    1,
    8,
]
d_hidden_factor = [
    "uniform",
    1.0,
    4.0,
]
dropout_first = [
    "uniform",
    0.0,
    0.5,
]
dropout_second = [
    "?uniform",
    0.0,
    0.0,
    0.5,
]

[space.pretrain]
corrupt_probability = [
    "uniform",
    0.2,
    0.8,
]

[space.training]
lr = [
    "loguniform",
    5e-05,
    0.005,
]
weight_decay = [
    "?loguniform",
    0.0,
    1e-06,
    0.001,
]
