seed = 8

[data]
path = "data/fb-comments"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"

[xgboost]
booster = "gbtree"
n_estimators = 2000
n_jobs = 1
tree_method = "gpu_hist"
colsample_bytree = 0.9450318120451608
gamma = 0
lambda = 0.0
learning_rate = 0.043896812067912336
max_depth = 8
min_child_weight = 1.3337404303435096
subsample = 0.9918136631749961

[xgboost_fit]
early_stopping_rounds = 50
verbose = true
