seed = 3

[data]
path = "data/fb-comments"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.3238607214378165
depth = 10
l2_leaf_reg = 2.5149547862614354
leaf_estimation_iterations = 4
learning_rate = 0.1107904311024969

[catboost_fit]
logging_level = "Verbose"
