seed = 9

[data]
path = "data/gesture"
T_cache = false

[data.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[catboost]
iterations = 2000
early_stopping_rounds = 50
od_pval = 0.001
task_type = "CPU"
thread_count = 4
bagging_temperature = 0.5522884125601488
depth = 7
l2_leaf_reg = 7.768763095027453
leaf_estimation_iterations = 10
learning_rate = 0.2419901981975169

[catboost_fit]
logging_level = "Verbose"
